### ISSUE TITLE
RAM Memory renders as	 unlimited

### ISSUE THREAD

**Issue by mkostrikin** [sibprogrammer/owp#29]
- OpenVZ Web Panel 2.4
- 1007 freshly created

> $ grep PHYSPAGES /etc/vz/conf/1007.conf
> 
> PHYSPAGES="0:256M"
- 1006 settings edited by OWP

> $ grep PHYSPAGES /etc/vz/conf/1006.conf
> 
> PHYSPAGES="0:262144"
- after Synchronization panel shows for RAM column:

> 1006 - unlimited
> 
> 1007 - 256
- If I change setting with OWP, panel render latest value, but after sync button becomes unlimited

Thanks

**Comment by dhewana** [comment]
Hi,

Need some help here.

This also happened to me (OpenVZ Web Panel 2.4).

![capture2a](https://cloud.githubusercontent.com/assets/11808969/9518473/23ab9db0-4ce1-11e5-8d1e-33fd971e51f3.jpg)

![capture3a](https://cloud.githubusercontent.com/assets/11808969/9518495/3ca695e0-4ce1-11e5-86cd-e22905c0c309.jpg)


When I tried to change the vm settings (in this case changing the Server Template), this error happened:

![capture4a](https://cloud.githubusercontent.com/assets/11808969/9518499/48a483e8-4ce1-11e5-9f12-55b9b1a67675.jpg)

I've also tried this fix https://github.com/sibprogrammer/owp/commit/0acd1bf97971deb9433e77f751b1e703aba30389 but still doesn't work.

Thank you.

**Comment by dhewana** [comment]
* After digging into the log:

~# tail -f /opt/ovz-web-panel/log/production.log

Processing Admin::VirtualServersController#create (for 202.43.163.198 at 2015-08-27 20:50:40) [POST]
  Parameters: {"vswap"=>"", "cpu_limit"=>"", "host_name"=>"sandbox-dhewana", "password_confirmation"=>"[FILTERED]", "nameserver"=>"", "memory"=>"unlimited", "search_domain"=>"", "controller"=>"admin/virtual_servers", "description"=>"", "start_on_boot"=>"on", "orig_server_template"=>"vswap-1g", "ip_address"=>"172.16.16.107", "cpu_units"=>"1000", "action"=>"create", "password"=>"[FILTERED]", "start_after_creation"=>"", "id"=>"22", "diskspace"=>"2252", "cpus"=>"", "expiration_date"=>"", "hardware_server_id"=>"2", "user_id"=>"6"}
Executing command: vzctl set 7 --privvmpages unlimited --save
Executing command: vzctl set 7 --physpages unlimited --save

HwDaemonExecException (Command 'vzctl set 7 --physpages unlimited --save' execution failed with code 1
Output: setublimit TCPSNDBUF 9223372036855300095:9223372036854775807 failed: Invalid argument
Error: failed to apply some parameters, not saving configuration file!


* I suspect these lines of codes that causing the problem :

https://github.com/sibprogrammer/owp/blob/master/app/models/virtual_server.rb#L144-L152

      if memory_changed?
        if vswap and vswap > 0 and hardware_server.vswap
          vzctl_set("--ram #{shellescape(memory.to_s)}M --save")
        else
          privvmpages = 0 == memory.to_i ? 'unlimited' : memory.to_i * 1024 / 4
          vzctl_set("--privvmpages #{shellescape(privvmpages.to_s)} --save")
          vzctl_set("--physpages unlimited --save")
        end
      end

Waiting for your confirmation.
Thanks.

**Comment by phlegx** [comment]
Same problem! Do you have found a solution @dhewana?

**Comment by dhewana** [comment]
@phlegx unfortunately no..

I decided to move to proxmox 3.4, which also supported openzv, but I had to manually recreate the vm and then migrate/transfer my data and settings because proxmox 3.4 doesn't seem compatible with vm that created using openvz-web-panel.

Currently, I use proxmox 4.0, which replaced openvz with lxc, and it's easy to transfer/convert from openvz in proxmox 3.4 to lxc in proxmox 4.0.
