### ISSUE TITLE
Move doc to Wiki

### ISSUE THREAD

**Issue by PunKeel** [sibprogrammer/owp#57]
Hi,

The Remote API documentation is no more up to date, and is not even on Github. Google code being shut down soon, it might be a good idea to consider moving it to Github, and updating it (for example, ip-pools is missing)

Thanks!

**Comment by cybernet** [comment]
+1

**Comment by EnguerrandP** [comment]
I approve

**Comment by cybernet** [comment]
and this ticket is still open !!!
why ?
