### ISSUE TITLE
URL no available

### ISSUE THREAD

**Issue by slorenzot** [sibprogrammer/owp#68]
The url for autoinstaller http://owp.softunity.com.ru/download/ovz-web-panel-latest.tgz is not available

thanks!

**Comment by donothesitate** [comment]
@slorenzot 

Use wayback:
wget -O - https://raw.githubusercontent.com/sibprogrammer/owp/master/installer/ai.sh | \
sh -s DOWNLOAD_URL=http://web.archive.org/web/20160804064250/http://ovz-web-panel.googlecode.com/files/ovz-web-panel-2.4.tgz
